/**
 * This code was generated by Builder.io.
 */
import Image from "next/image";
import * as React from "react";

function MyComponent(props) {
  return (
    <div className="justify-center pb-2 px-20 max-md:px-5">
      <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
        <div className="flex flex-col items-stretch w-[52%] max-md:w-full max-md:ml-0">
          <span className="flex flex-col my-auto max-md:max-w-full max-md:mt-10">
            <div className="text-teal-500 text-lg font-bold leading-7 tracking-normal uppercase self-stretch max-md:max-w-full">
              Why choose us
            </div>
            <div className="text-black text-lg font-bold leading-7 tracking-normal uppercase self-stretch mt-16 max-md:max-w-full max-md:mt-10">
              Boosts Your Website Traffic!
            </div>
            <div className="text-black text-lg leading-7 tracking-normal uppercase self-stretch mt-14 max-md:max-w-full max-md:mt-10">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras{" "}
              <br /> bibendum auctor justo, ac bibendum neque sollicitudin ac.{" "}
              <br /> Duis feugiat non urna nec tincidunt. Sed nec est eget sem{" "}
              <br /> sodales ultricies vitae a elit. Donec velit massa <br />{" "}
              dapibus eu facilisis eu.
            </div>
            <button className="items-stretch shadow-sm bg-purple-600 flex w-[219px] max-w-full flex-col justify-center mt-8 px-10 py-4 rounded-3xl self-start max-md:px-5">
              <span className="justify-between items-stretch flex gap-3 px-0.5">
                <div className="text-white text-center text-base font-bold leading-5 capitalize grow whitespace-nowrap">
                  More About us
                </div>
                <div className="text-white text-center text-base font-black leading-4 capitalize self-center whitespace-nowrap my-auto">
                  
                </div>
              </span>
            </button>
          </span>
        </div>
        <div className="flex flex-col items-stretch w-[48%] ml-5 max-md:w-full max-md:ml-0">
          <Image
            loading="lazy"
            src="/path/to/image.jpg"
            alt="Description of the image"
            layout="responsive"
            width={1000}
            height={1340}
            className="aspect-[1.34] object-contain object-center w-full overflow-hidden grow max-md:max-w-full max-md:mt-10"
          />
        </div>
      </div>
    </div>
  );
}
