/**
 * This code was generated by Builder.io.
 */
"use client";
import * as React from "react";

function Navbar(props) {
  return (
    <div
      className="flex flex-col relative shrink-0 box-border h-auto grow-0 shadow-sm px-5 py-2"
      maxWidth={null}
      lazyLoad={false}
    >
      <section className="flex flex-col relative shrink-0 box-border h-auto grow shadow-sm w-full self-stretch max-w-[1200px] items-stretch mx-auto px-5 py-2">
        <div className="flex flex-row w-full max-md:justify-start max-md:items-start max-sm:items-center">
          <div className="relative self-stretch flex flex-row gap-5 justify-between w-full items-center my-3">
            <div className="flex flex-row grow-[1.1674179080885916] self-stretch relative max-md:items-center max-md:w-full max-md:mr-auto max-md:my-auto max-sm:justify-start">
              <img
                loading="lazy"
                srcSet="https://cdn.builder.io/api/v1/image/assets%2Fb92c28b7e5bf4bd9bd0a2ebf4f92d5f5%2Fa9221283177b4bfc98467fbd96ea4533?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2Fb92c28b7e5bf4bd9bd0a2ebf4f92d5f5%2Fa9221283177b4bfc98467fbd96ea4533?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2Fb92c28b7e5bf4bd9bd0a2ebf4f92d5f5%2Fa9221283177b4bfc98467fbd96ea4533?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2Fb92c28b7e5bf4bd9bd0a2ebf4f92d5f5%2Fa9221283177b4bfc98467fbd96ea4533?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2Fb92c28b7e5bf4bd9bd0a2ebf4f92d5f5%2Fa9221283177b4bfc98467fbd96ea4533?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2Fb92c28b7e5bf4bd9bd0a2ebf4f92d5f5%2Fa9221283177b4bfc98467fbd96ea4533?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2Fb92c28b7e5bf4bd9bd0a2ebf4f92d5f5%2Fa9221283177b4bfc98467fbd96ea4533?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2Fb92c28b7e5bf4bd9bd0a2ebf4f92d5f5%2Fa9221283177b4bfc98467fbd96ea4533"
                className="aspect-[0.29] object-cover object-center w-full shrink-0 box-border min-h-[20px] min-w-[20px] overflow-hidden max-h-12 max-w-[91px] mx-auto max-md:w-auto max-md:grow max-md:mr-auto max-sm:max-h-[42px] max-sm:max-w-[53px] max-sm:min-w-[42px] max-sm:mr-auto"
              />
              <div className="relative flex flex-col grow-[3.1608208817763215] mt-4 max-md:hidden max-md:flex-row max-md:mr-auto max-sm:hidden">
                <div className="relative self-stretch flex flex-row gap-4 justify-start max-md:justify-center">
                  <div className="relative shrink-0 box-border">Home</div>
                  <div className="relative shrink-0 box-border">
                    Services
                    <br />
                    <br />
                  </div>
                  <div className="relative shrink-0 box-border ml-0.5 max-md:mx-0.5">
                    Project
                    <br />
                    <br />
                  </div>
                  <div className="relative shrink-0 box-border ml-3 max-md:mx-2.5">
                    About
                    <br />
                    <br />
                  </div>
                  <div className="relative shrink-0 box-border ml-3 max-md:mx-2.5">
                    Contact
                    <br />
                    <br />
                  </div>
                </div>
              </div>
            </div>
            <div className="relative flex flex-row grow-0 w-auto ml-auto mt-px max-md:hidden max-sm:hidden">
              <div className="relative flex flex-row gap-4 ml-4">
                <button className="text-white text-center text-lg font-bold leading-4 uppercase whitespace-nowrap items-stretch self-center justify-center bg-purple-600 accent-[hex8F00FF] my-auto px-8 py-5 rounded-3xl max-md:px-5">
                  Get a Quote
                </button>
              </div>
            </div>
          </div>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F0663bd40b99a4259a807f6f0014df73d"
            className="aspect-[3.87] object-cover object-center w-full shrink-0 box-border min-h-[20px] min-w-[20px] overflow-hidden mt-5 max-md:flex max-md:max-w-[48px] max-md:w-6 max-md:h-6 max-sm:h-6 max-sm:w-6 max-sm:flex max-sm:ml-auto"
          />
        </div>
        {show ? (
          <div
            gridRowWidth="25%"
            className="flex flex-col relative shrink-0 box-border items-stretch mt-5 max-md:flex max-sm:flex"
            items={[
              {
                title: [
                  {
                    "@type": "@builder.io/sdk:Element",
                    "@version": 2,
                    layerName: "Accordion item title",
                    id: "builder-55066ec422f64f4a92216529058bf193",
                    children: [
                      {
                        "@type": "@builder.io/sdk:Element",
                        "@version": 2,
                        layerName: "Home",
                        id: "builder-90a850668b874461ad2f2791f30a0311",
                        component: {
                          name: "Text",
                          options: {
                            text: "Product",
                          },
                        },
                        responsiveStyles: {
                          large: {
                            textAlign: "left",
                            display: "flex",
                            flexDirection: "column",
                          },
                        },
                      },
                    ],
                    responsiveStyles: {
                      large: {
                        position: "relative",
                        display: "flex",
                        alignItems: "stretch",
                        flexDirection: "column",
                        paddingBottom: "10px",
                        backgroundColor: "rgba(234, 234, 234, 1)",
                        paddingLeft: "10px",
                        paddingRight: "10px",
                        paddingTop: "10px",
                      },
                      medium: {
                        backgroundColor: "rgba(255, 255, 255, 1)",
                      },
                    },
                  },
                ],
                detail: [],
              },
              {
                title: [
                  {
                    "@type": "@builder.io/sdk:Element",
                    "@version": 2,
                    layerName: "Accordion item title",
                    id: "builder-14a2c33680a6457993c5c5f0e5e41751",
                    children: [
                      {
                        "@type": "@builder.io/sdk:Element",
                        "@version": 2,
                        layerName: "Services",
                        id: "builder-edeb6a37d57c4e9e8b4b815258b7aa8b",
                        component: {
                          name: "Text",
                          options: {
                            text: "Solution",
                          },
                        },
                        responsiveStyles: {
                          large: {
                            textAlign: "left",
                            display: "flex",
                            flexDirection: "column",
                          },
                        },
                      },
                    ],
                    responsiveStyles: {
                      large: {
                        position: "relative",
                        display: "flex",
                        alignItems: "stretch",
                        flexDirection: "column",
                        paddingBottom: "10px",
                        backgroundColor: "rgba(234, 234, 234, 1)",
                        paddingLeft: "10px",
                        paddingRight: "10px",
                        paddingTop: "10px",
                      },
                      medium: {
                        backgroundColor: "rgba(255, 255, 255, 1)",
                      },
                    },
                  },
                  {
                    "@type": "@builder.io/sdk:Element",
                    "@version": 2,
                    layerName: "Accordion item title",
                    id: "builder-52be1d50346045a6ac4c81f1d2d79d94",
                    meta: {
                      previousId: "builder-14a2c33680a6457993c5c5f0e5e41751",
                    },
                    children: [
                      {
                        "@type": "@builder.io/sdk:Element",
                        "@version": 2,
                        layerName: "Project",
                        id: "builder-79ddbcd8590a4ec5a0258e4f55bf2dec",
                        meta: {
                          previousId:
                            "builder-edeb6a37d57c4e9e8b4b815258b7aa8b",
                        },
                        component: {
                          name: "Text",
                          options: {
                            text: "Solution",
                          },
                        },
                        responsiveStyles: {
                          large: {
                            textAlign: "left",
                            display: "flex",
                            flexDirection: "column",
                          },
                        },
                      },
                    ],
                    responsiveStyles: {
                      large: {
                        position: "relative",
                        display: "flex",
                        alignItems: "stretch",
                        flexDirection: "column",
                        paddingBottom: "10px",
                        backgroundColor: "rgba(234, 234, 234, 1)",
                        paddingLeft: "10px",
                        paddingRight: "10px",
                        paddingTop: "10px",
                      },
                      medium: {
                        backgroundColor: "rgba(255, 255, 255, 1)",
                      },
                    },
                  },
                ],
                detail: [],
              },
              {
                title: [
                  {
                    "@type": "@builder.io/sdk:Element",
                    "@version": 2,
                    layerName: "Accordion item title",
                    id: "builder-55a8bc5999b748c1a1bfd8bcc124a8e5",
                    children: [
                      {
                        "@type": "@builder.io/sdk:Element",
                        "@version": 2,
                        layerName: "About",
                        id: "builder-1f0f00b4fcba47e0b58bbe7e7890f977",
                        component: {
                          name: "Text",
                          options: {
                            text: "Resources",
                          },
                        },
                        responsiveStyles: {
                          large: {
                            textAlign: "left",
                            display: "flex",
                            flexDirection: "column",
                          },
                        },
                      },
                    ],
                    responsiveStyles: {
                      large: {
                        position: "relative",
                        display: "flex",
                        alignItems: "stretch",
                        flexDirection: "column",
                        paddingBottom: "10px",
                        backgroundColor: "rgba(234, 234, 234, 1)",
                        paddingLeft: "10px",
                        paddingRight: "10px",
                        paddingTop: "10px",
                      },
                      medium: {
                        backgroundColor: "rgba(255, 255, 255, 1)",
                      },
                    },
                  },
                  {
                    "@type": "@builder.io/sdk:Element",
                    "@version": 2,
                    layerName: "Accordion item title",
                    id: "builder-81a2b18bb31449b4a70144af14ff41f5",
                    meta: {
                      previousId: "builder-55a8bc5999b748c1a1bfd8bcc124a8e5",
                    },
                    children: [
                      {
                        "@type": "@builder.io/sdk:Element",
                        "@version": 2,
                        layerName: "Contact",
                        id: "builder-1eba215b8449496eb8b8fa1944d543d8",
                        meta: {
                          previousId:
                            "builder-1f0f00b4fcba47e0b58bbe7e7890f977",
                        },
                        component: {
                          name: "Text",
                          options: {
                            text: "Resources",
                          },
                        },
                        responsiveStyles: {
                          large: {
                            textAlign: "left",
                            display: "flex",
                            flexDirection: "column",
                          },
                        },
                      },
                    ],
                    responsiveStyles: {
                      large: {
                        position: "relative",
                        display: "flex",
                        alignItems: "stretch",
                        flexDirection: "column",
                        paddingBottom: "10px",
                        backgroundColor: "rgba(234, 234, 234, 1)",
                        paddingLeft: "10px",
                        paddingRight: "10px",
                        paddingTop: "10px",
                      },
                      medium: {
                        backgroundColor: "rgba(255, 255, 255, 1)",
                      },
                    },
                  },
                ],
                detail: [],
              },
            ]}
            oneAtATime={(event) => false}
            grid={false}
            useChildrenForItems={false}
          >
            <div>
              <div builder="accordion">
                <div builder="accordion-title">
                  <div
                    builder-id="builder-55066ec422f64f4a92216529058bf193"
                    className="relative flex items-stretch flex-col bg-gray-200 p-2.5 max-md:bg-white"
                  >
                    <div
                      builder-id="builder-90a850668b874461ad2f2791f30a0311"
                      className="text-left flex flex-col"
                    >
                      <div
                        dangerouslySetInnerHTML={{ __html: Product }}
                        className="builder-text"
                      />
                    </div>
                  </div>
                </div>
                <div builder="accordion-detail" />
              </div>
              <div builder="accordion">
                <div builder="accordion-title">
                  <div
                    builder-id="builder-14a2c33680a6457993c5c5f0e5e41751"
                    className="relative flex items-stretch flex-col bg-gray-200 p-2.5 max-md:bg-white"
                  >
                    <div
                      builder-id="builder-edeb6a37d57c4e9e8b4b815258b7aa8b"
                      className="text-left flex flex-col"
                    >
                      <div
                        dangerouslySetInnerHTML={{ __html: Solution }}
                        className="builder-text"
                      />
                    </div>
                  </div>
                  <div
                    builder-id="builder-52be1d50346045a6ac4c81f1d2d79d94"
                    className="relative flex items-stretch flex-col bg-gray-200 p-2.5 max-md:bg-white"
                  >
                    <div
                      builder-id="builder-79ddbcd8590a4ec5a0258e4f55bf2dec"
                      className="text-left flex flex-col"
                    >
                      <div
                        dangerouslySetInnerHTML={{ __html: Solution }}
                        className="builder-text"
                      />
                    </div>
                  </div>
                </div>
                <div builder="accordion-detail" />
              </div>
              <div builder="accordion">
                <div builder="accordion-title">
                  <div
                    builder-id="builder-55a8bc5999b748c1a1bfd8bcc124a8e5"
                    className="relative flex items-stretch flex-col bg-gray-200 p-2.5 max-md:bg-white"
                  >
                    <div
                      builder-id="builder-1f0f00b4fcba47e0b58bbe7e7890f977"
                      className="text-left flex flex-col"
                    >
                      <div
                        dangerouslySetInnerHTML={{ __html: Resources }}
                        className="builder-text"
                      />
                    </div>
                  </div>
                  <div
                    builder-id="builder-81a2b18bb31449b4a70144af14ff41f5"
                    className="relative flex items-stretch flex-col bg-gray-200 p-2.5 max-md:bg-white"
                  >
                    <div
                      builder-id="builder-1eba215b8449496eb8b8fa1944d543d8"
                      className="text-left flex flex-col"
                    >
                      <div
                        dangerouslySetInnerHTML={{ __html: Resources }}
                        className="builder-text"
                      />
                    </div>
                  </div>
                </div>
                <div builder="accordion-detail" />
              </div>
            </div>
          </div>
        ) : null}
      </section>
    </div>
  );
}
