/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Image from "next/image";

function HomePage(props) {
  return (
    <div className="justify-center items-stretch bg-neutral-100 flex flex-col">
      <header className="flex-col overflow-hidden relative flex min-h-[512px] w-full justify-center items-stretch py-3 max-md:max-w-full">
        <Image
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/1c4fe0895cb4892645e9e37c8f685cb122d13bb59ed7c143125f68ca7219b93a?apiKey=b92c28b7e5bf4bd9bd0a2ebf4f92d5f5"
          alt="Background Image"
          className="absolute h-full w-full object-cover object-center inset-0"
        />
        <div className="relative flex flex-col max-md:mt-10">
          <div className="max-w-full justify-center relative w-[1140px] mx-auto px-3 py-6 max-md:pl-5">
            <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
              <div className="flex flex-col items-stretch w-[45%] max-md:w-full max-md:ml-0">
                <div className="text-teal-500 text-lg font-bold leading-7 tracking-normal uppercase self-stretch">
                  Get free quote for
                </div>
                <div className="justify-center text-black text-5xl font-bold leading-7 capitalize self-stretch mt-16 mb-5 max-md:text-4xl max-md:leading-6 max-md:mt-10">
                  Search Engine <br /> <br /> Optimization.
                </div>
                <button className="text-white text-center text-lg font-bold leading-4 uppercase whitespace-nowrap items-stretch self-center justify-center bg-purple-600 accent-[hex8F00FF] mr-auto my-auto px-8 py-5 rounded-3xl max-md:px-5">
                  More About us
                </button>
                <Image
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/fc7d4798d1764b7cf2556acde6dba22d646a7ad7dd671095534541bd5ee0dc66?apiKey=b92c28b7e5bf4bd9bd0a2ebf4f92d5f5"
                  alt="Image 1"
                  className="aspect-[4.83] object-contain object-center w-[285px] max-w-full overflow-hidden mt-14 self-start max-md:mt-10"
                />
              </div>
              <div className="flex flex-col items-stretch w-[55%] ml-5 max-md:w-full max-md:ml-0">
                <Image
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/44c5598ab76bdc47c854f24beafc59b12202f50a5db5d59c3b8230996dbe9d44?apiKey=b92c28b7e5bf4bd9bd0a2ebf4f92d5f5"
                  alt="Image 2"
                  className="aspect-[1.42] object-contain object-center w-full overflow-hidden grow max-md:max-w-full max-md:mt-10"
                />
              </div>
            </div>
          </div>
        </div>
      </header>
    </div>
  );
}
