/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Image from "next/image";

function Roi(props) {
  return (
    <form className="items-stretch self-stretch flex flex-col pb-12">
      <header className="justify-center w-full -mr-0.5 mt-5 mb-3.5 pr-20 max-md:max-w-full max-md:ml-0 max-md:px-5">
        <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
          <div className="flex flex-col items-stretch w-[33%] max-md:w-full max-md:ml-0">
            <a
              href="..."
              className="items-center bg-white flex-grow flex-col w-full pb-12 max-md:mt-9 max-md:px-2.5"
              aria-label="Significant ROI"
            >
              <Image
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/1c4fe0895cb4892645e9e37c8f685cb122d13bb59ed7c143125f68ca7219b93a?apiKey=b92c28b7e5bf4bd9bd0a2ebf4f92d5f5"
                className="aspect-square object-contain object-center w-[120px] overflow-hidden self-center max-w-full"
                aria-role="presentation"
                width={120}
                height={120}
              />
              <div className="text-neutral-700 text-center text-xl font-bold leading-8 self-center whitespace-nowrap mt-14 max-md:mt-10">
                Significant ROI
              </div>
              <div className="text-black text-center text-base leading-6 self-stretch mt-5">
                Description Lorem ipsum dolor sit <br /> amet, consectetur
                adipiscing elit.
                <br /> Aliquam in placerat elit, consequat <br /> tristique
              </div>
              <a
                href="..."
                className="text-center text-xl font-bold leading-8 bg-clip-text bg-[linear-gradient(269deg,#8F00FF_0%,#C356F7_50%,#7000FF_100%)] self-center whitespace-nowrap mt-5"
              >
                Read More
              </a>
            </a>
          </div>
          <div className="flex flex-col items-stretch w-[33%] ml-5 max-md:w-full max-md:ml-0">
            <a
              href="..."
              className="items-center bg-white flex-grow flex-col w-full pb-12 max-md:mt-9 max-md:px-2.5"
              aria-label="Significant ROI"
            >
              <Image
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/fc7d4798d1764b7cf2556acde6dba22d646a7ad7dd671095534541bd5ee0dc66?apiKey=b92c28b7e5bf4bd9bd0a2ebf4f92d5f5"
                className="aspect-square object-contain object-center w-[120px] overflow-hidden self-center max-w-full"
                aria-role="presentation"
                width={120}
                height={120}
              />
              <div className="text-neutral-700 text-center text-xl font-bold leading-8 self-center whitespace-nowrap mt-14 max-md:mt-10">
                Significant ROI
              </div>
              <div className="text-black text-center text-base leading-6 self-stretch mt-5">
                Description Lorem ipsum dolor sit <br /> amet, consectetur
                adipiscing elit.
                <br /> Aliquam in placerat elit, consequat <br /> tristique
              </div>
              <a
                href="..."
                className="text-center text-xl font-bold leading-8 bg-clip-text bg-[linear-gradient(269deg,#8F00FF_0%,#C356F7_50%,#7000FF_100%)] self-center whitespace-nowrap mt-5"
              >
                Read More
              </a>
            </a>
          </div>
          <div className="flex flex-col items-stretch w-[33%] ml-5 max-md:w-full max-md:ml-0">
            <a
              href="..."
              className="items-center bg-white flex-grow flex-col w-full pb-12 max-md:mt-9 max-md:px-2.5"
              aria-label="Significant ROI"
            >
              <Image
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/44c5598ab76bdc47c854f24beafc59b12202f50a5db5d59c3b8230996dbe9d44?apiKey=b92c28b7e5bf4bd9bd0a2ebf4f92d5f5"
                className="aspect-square object-contain object-center w-[120px] overflow-hidden self-center max-w-full"
                aria-role="presentation"
                width={120}
                height={120}
              />
              <div className="text-neutral-700 text-center text-xl font-bold leading-8 self-center whitespace-nowrap mt-14 max-md:mt-10">
                Significant ROI
              </div>
              <div className="text-black text-center text-base leading-6 self-stretch mt-5">
                Description Lorem ipsum dolor sit <br /> amet, consectetur
                adipiscing elit.
                <br /> Aliquam in placerat elit, consequat <br /> tristique
              </div>
              <a
                href="..."
                className="text-center text-xl font-bold leading-8 bg-clip-text bg-[linear-gradient(269deg,#8F00FF_0%,#C356F7_50%,#7000FF_100%)] self-center whitespace-nowrap mt-5"
              >
                Read More
              </a>
            </a>
          </div>
        </div>
      </header>
    </form>
  );
}
export default Roi