/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Image from "next/image";

function StandingDigi(props) {
  return (
    <section className="items-stretch self-stretch flex flex-col pb-12">
      <header className="text-teal-500 text-center text-sm font-extrabold leading-8 uppercase self-center whitespace-nowrap">
        SEARCH ENGINE &amp; SOCIAL MEDIA OPTIMIZATION
      </header>
      <h1 className="text-neutral-700 text-center text-3xl font-extrabold leading-10 self-center mt-2 max-md:max-w-full">
        Full Service Digital Marketing Agency
      </h1>
      <div className="justify-center w-full -mr-0.5 mt-5 mb-3.5 pr-20 max-md:max-w-full max-md:ml-0 max-md:px-5">
        <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
          <form className="flex flex-col items-stretch w-[33%] max-md:w-full max-md:ml-0">
            <div
              className="items-center bg-white flex grow flex-col w-full pb-12 max-md:mt-9 max-md:px-2.5"
              aria-label="Significant ROI"
              role="region"
            >
              <Image
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/1c4fe0895cb4892645e9e37c8f685cb122d13bb59ed7c143125f68ca7219b93a?apiKey=b92c28b7e5bf4bd9bd0a2ebf4f92d5f5"
                alt="ROI Graphic"
                layout="responsive"
                width={120}
                height={120}
                className="aspect-square object-contain object-center w-[120px] overflow-hidden self-center max-w-full"
              />
              <h2 className="text-neutral-700 text-center text-xl font-bold leading-8 self-center whitespace-nowrap mt-14 max-md:mt-10">
                Significant ROI
              </h2>
              <div className="text-black text-center text-base leading-6 self-stretch mt-5">
                Description Lorem ipsum dolor sit <br /> amet, consectetur
                adipiscing elit. <br /> Aliquam in placerat elit, consequat{" "}
                <br /> tristique{" "}
              </div>
              <a
                href="#"
                className="text-center text-xl font-bold leading-8 bg-clip-text bg-[linear-gradient(269deg,#8F00FF_0%,#C356F7_50%,#7000FF_100%)] self-center whitespace-nowrap mt-5"
              >
                Read More
              </a>
            </div>
          </form>
          <form className="flex flex-col items-stretch w-[33%] ml-5 max-md:w-full max-md:ml-0">
            <div
              className="items-center bg-white flex grow flex-col w-full pb-12 max-md:mt-9 max-md:px-2.5"
              aria-label="Significant ROI"
              role="region"
            >
              <Image
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/fc7d4798d1764b7cf2556acde6dba22d646a7ad7dd671095534541bd5ee0dc66?apiKey=b92c28b7e5bf4bd9bd0a2ebf4f92d5f5"
                alt="ROI Graphic"
                layout="responsive"
                width={120}
                height={120}
                className="aspect-square object-contain object-center w-[120px] overflow-hidden self-center max-w-full"
              />
              <h2 className="text-neutral-700 text-center text-xl font-bold leading-8 self-center whitespace-nowrap mt-14 max-md:mt-10">
                Significant ROI
              </h2>
              <div className="text-black text-center text-base leading-6 self-stretch mt-5">
                Description Lorem ipsum dolor sit <br /> amet, consectetur
                adipiscing elit. <br /> Aliquam in placerat elit, consequat{" "}
                <br /> tristique{" "}
              </div>
              <a
                href="#"
                className="text-center text-xl font-bold leading-8 bg-clip-text bg-[linear-gradient(269deg,#8F00FF_0%,#C356F7_50%,#7000FF_100%)] self-center whitespace-nowrap mt-5"
              >
                Read More
              </a>
            </div>
          </form>
          <form className="flex flex-col items-stretch w-[33%] ml-5 max-md:w-full max-md:ml-0">
            <div
              className="items-center bg-white flex grow flex-col w-full pb-12 max-md:mt-9 max-md:px-2.5"
              aria-label="Significant ROI"
              role="region"
            >
              <Image
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/44c5598ab76bdc47c854f24beafc59b12202f50a5db5d59c3b8230996dbe9d44?apiKey=b92c28b7e5bf4bd9bd0a2ebf4f92d5f5"
                alt="ROI Graphic"
                layout="responsive"
                width={120}
                height={120}
                className="aspect-square object-contain object-center w-[120px] overflow-hidden self-center max-w-full"
              />
              <h2 className="text-neutral-700 text-center text-xl font-bold leading-8 self-center whitespace-nowrap mt-14 max-md:mt-10">
                Significant ROI
              </h2>
              <div className="text-black text-center text-base leading-6 self-stretch mt-5">
                Description Lorem ipsum dolor sit <br /> amet, consectetur
                adipiscing elit. <br /> Aliquam in placerat elit, consequat{" "}
                <br /> tristique{" "}
              </div>
              <a
                href="#"
                className="text-center text-xl font-bold leading-8 bg-clip-text bg-[linear-gradient(269deg,#8F00FF_0%,#C356F7_50%,#7000FF_100%)] self-center whitespace-nowrap mt-5"
              >
                Read More
              </a>
            </div>
          </form>
        </div>
      </div>
    </section>
  );
}

export default StandingDigi;
