/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Image from "next/image";

function ImageGallery(props) {
  return (
    <form>
      <div className="header">
        <header className="header"></header>
      </div>

      <div className="justify-between items-stretch bg-slate-50 flex gap-5 pl-20 py-10 max-md:flex-wrap max-md:pl-5">
        <a href="...">
          <Image
            loading="lazy"
            src="..."
            className="aspect-square object-contain object-center w-[150px] overflow-hidden shrink-0 max-w-full"
            alt="Image 1"
          />
        </a>

        <a href="...">
          <Image
            loading="lazy"
            src="..."
            className="aspect-square object-contain object-center w-[150px] overflow-hidden shrink-0 max-w-full"
            alt="Image 2"
          />
        </a>

        <a href="...">
          <Image
            loading="lazy"
            src="..."
            className="aspect-square object-contain object-center w-[150px] overflow-hidden shrink-0 max-w-full"
            alt="Image 3"
          />
        </a>

        <a href="...">
          <Image
            loading="lazy"
            src="..."
            className="aspect-square object-contain object-center w-[150px] overflow-hidden shrink-0 max-w-full"
            alt="Image 4"
          />
        </a>

        <a href="...">
          <Image
            loading="lazy"
            src="..."
            className="aspect-[0.89] object-contain object-center w-[133px] overflow-hidden shrink-0 max-w-full"
            alt="Image 5"
          />
        </a>
      </div>
    </form>
  );
}
