/**
 * This code was generated by Builder.io.
 */
import * as React from "react";
import Image from "next/image";

function UpdatedComponent(props) {
  return (
    <form className="justify-center px-20 max-md:px-5">
      <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
        <div className="flex flex-col items-stretch w-[48%] max-md:w-full max-md:ml-0">
          <Image
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/1c4fe0895cb4892645e9e37c8f685cb122d13bb59ed7c143125f68ca7219b93a?apiKey=b92c28b7e5bf4bd9bd0a2ebf4f92d5f5"
            srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/fc7d4798d1764b7cf2556acde6dba22d646a7ad7dd671095534541bd5ee0dc66?apiKey=b92c28b7e5bf4bd9bd0a2ebf4f92d5f5&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/fc7d4798d1764b7cf2556acde6dba22d646a7ad7dd671095534541bd5ee0dc66?apiKey=b92c28b7e5bf4bd9bd0a2ebf4f92d5f5&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/fc7d4798d1764b7cf2556acde6dba22d646a7ad7dd671095534541bd5ee0dc66?apiKey=b92c28b7e5bf4bd9bd0a2ebf4f92d5f5&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/fc7d4798d1764b7cf2556acde6dba22d646a7ad7dd671095534541bd5ee0dc66?apiKey=b92c28b7e5bf4bd9bd0a2ebf4f92d5f5&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/fc7d4798d1764b7cf2556acde6dba22d646a7ad7dd671095534541bd5ee0dc66?apiKey=b92c28b7e5bf4bd9bd0a2ebf4f92d5f5&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/fc7d4798d1764b7cf2556acde6dba22d646a7ad7dd671095534541bd5ee0dc66?apiKey=b92c28b7e5bf4bd9bd0a2ebf4f92d5f5&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/fc7d4798d1764b7cf2556acde6dba22d646a7ad7dd671095534541bd5ee0dc66?apiKey=b92c28b7e5bf4bd9bd0a2ebf4f92d5f5&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/fc7d4798d1764b7cf2556acde6dba22d646a7ad7dd671095534541bd5ee0dc66?apiKey=b92c28b7e5bf4bd9bd0a2ebf4f92d5f5&"
            className="aspect-[1.31] object-contain object-center w-full overflow-hidden grow max-md:max-w-full max-md:mt-8"
            alt="Image"
          />
        </div>
        <div className="flex flex-col items-stretch w-[52%] ml-5 max-md:w-full max-md:ml-0">
          <header className="flex flex-col mt-4 max-md:max-w-full max-md:mt-10">
            <h2 className="text-teal-500 text-lg font-bold leading-7 tracking-normal uppercase self-stretch max-md:max-w-full">
              Grow Traffic & Increase Revenuezzzzz
            </h2>
            <h3 className="text-black text-lg font-bold leading-7 tracking-normal uppercase self-stretch mt-16 max-md:max-w-full max-md:mt-10">
              Appear On the Front Page of Google!
            </h3>
            <p className="text-black text-lg leading-7 tracking-normal uppercase self-stretch mt-14 max-md:max-w-full max-md:mt-10">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras{" "}
              <br /> bibendum auctor justo, ac bibendum neque sollicitudin ac.{" "}
              <br /> Duis feugiat non urna nec tincidunt. Sed nec est eget sem{" "}
              <br /> sodales ultricies vitae a elit. Donec velit massa <br />,
              dapibus eu facilisis eu.
            </p>
            <button
              className="items-stretch shadow-sm bg-purple-600 flex w-[219px] max-w-full flex-col justify-center mt-8 px-10 py-4 rounded-3xl self-start max-md:px-5"
              aria-label="More About us"
              role="button"
            >
              <span className="justify-between items-stretch flex gap-3 px-0.5">
                <div className="text-white text-center text-base font-bold leading-5 capitalize grow whitespace-nowrap">
                  More About us
                </div>
                <div className="text-white text-center text-base font-black leading-4 capitalize self-center whitespace-nowrap my-auto">
                  
                </div>
              </span>
            </button>
          </header>
        </div>
      </div>
    </form>
  );
}
