/**
 * This code was generated by Builder.io.
 */
import React from "react";

function RollinNos(props) {
  return (
    <div className="self-stretch w-auto max-w-[1826px] mt-10 mx-10 max-md:max-w-full">
      <header className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
        <div className="flex flex-col items-stretch w-6/12 max-md:w-full max-md:ml-0">
          <header className="text-teal-500 text-lg font-bold leading-7 tracking-normal uppercase pb-16 self-start max-md:max-w-full">
            Why choose us
          </header>
          <div className="text-black text-lg leading-7 tracking-normal uppercase -mr-1 max-md:max-w-full max-md:mt-10 max-sm:ml-1">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras
            <br /> bibendum auctor justo, ac bibendum neque sollicitudin ac.
            <br /> Duis feugiat non urna nec tincidunt. Sed nec est eget sem
            <br /> sodales ultricies vitae a elit. Donec velit massa
            <br /> dapibus eu facilisis eu.
          </div>
          <div className="text-black text-lg font-bold leading-7 tracking-normal uppercase grow shrink basis-auto mt-11 max-md:mt-10">
            Boosts Your Website Traffic!
          </div>
          <button className="items-stretch shadow-sm bg-purple-600 flex w-[219px] max-w-full flex-col justify-center mt-8 px-10 py-4 rounded-3xl self-start max-md:px-5">
            <span className="justify-between items-stretch flex gap-3 px-0.5">
              <a
                href="#"
                className="text-white text-center text-base font-bold leading-5 capitalize grow whitespace-nowrap"
              >
                More About us
              </a>
              <div className="text-white text-center text-base font-black leading-4 capitalize self-center whitespace-nowrap my-auto">
                
              </div>
            </span>
          </button>
        </div>
        <div className="flex flex-col items-stretch w-6/12 ml-5 max-md:w-full max-md:ml-0">
          <header className="self-center flex w-auto max-w-[1082px] justify-between gap-5 mt-3.5 items-start max-md:max-w-full max-md:flex-wrap">
            <span className="items-stretch bg-white self-stretch flex justify-between gap-5 rounded-3xl max-md:max-w-full max-md:flex-wrap"></span>
          </header>
          <a
            href="#"
            className="items-stretch bg-white self-stretch flex justify-between gap-5 mt-20 pb-5 rounded-3xl max-md:max-w-full max-md:flex-wrap"
          >
            <a
              href="#"
              className="text-white text-xs font-black leading-loose justify-center items-stretch bg-teal-400 w-auto grow px-1 py-5 rounded-3xl max-sm:w-auto max-sm:grow"
            >
              <span className="text-xl">20+</span> <br /> <br />
              <span className="text-xs">EMPLOYEES</span>
            </a>
            <div className="text-black text-base leading-6 grow shrink basis-auto">
              Description Lorem ipsum dolor sit <br /> amet, consectetur
              adipiscing elit. <br /> Aliquam .
            </div>
          </a>
          <a
            href="#"
            className="items-stretch bg-white flex justify-between gap-5 w-full mt-3 pb-5 rounded-3xl max-md:max-w-full max-md:flex-wrap max-md:mt-10"
          >
            <a
              href="#"
              className="text-white text-sm font-black leading-3 justify-center items-stretch bg-teal-400 w-auto grow px-1.5 py-5 rounded-3xl"
            >
              <span className="text-xl">150+</span> <br />
              <span className="text-xs">CLIENTS</span>
            </a>
            <div className="text-black text-base leading-6 grow shrink basis-auto">
              Description Lorem ipsum dolor sit <br /> amet, consectetur
              adipiscing elit. <br /> Aliquam .
            </div>
          </a>
          <a
            href="#"
            className="items-stretch bg-white flex justify-between gap-5 w-full mt-3 pb-5 rounded-3xl max-md:max-w-full max-md:flex-wrap max-md:mt-10"
          >
            <a
              href="#"
              className="text-white text-sm font-black leading-3 justify-center items-stretch bg-teal-400 w-auto grow px-1.5 py-5 rounded-3xl"
            >
              <span className="text-xl">150+</span> <br />
              <span className="text-xs">CLIENTS</span>
            </a>
            <div className="text-black text-base leading-6 grow shrink basis-auto">
              Description Lorem ipsum dolor sit <br /> amet, consectetur
              adipiscing elit. <br /> Aliquam .
            </div>
          </a>
        </div>
      </header>
    </div>
  );
}
export default RollinNos